config/routes.rb
TwitterNeo::Application.routes.draw do
  devise_for :users
  root to:"static_pages#home"

  get 'help', to: "static_pages#help"

  resources :users, only:[:index, :show]
  resources :tweets, only: [:create]

  

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	scope :restricted, :conditions => ['relationships.restricted = ?', true]
  scope :unrestricted, :conditions => ['relationships.restricted = ?', false]
	
  scope :to_type, lambda {|rtype| rtype = [rtype].flatten.compact; rtype.size > 0 && {:conditions => ['relationships.requestee_type IN (?)', [rtype].flatten]} || {}}
  scope :from_type, lambda {|rtype| rtype = [rtype].flatten.compact; rtype.size > 0 && {:conditions => ['relationships.requestor_type IN (?)', [rtype].flatten]} || {}}
	
	default_scope :order => 'created_at DESC'
	
	with_options :polymorphic => true do |klazz|
		klazz.belongs_to :requestor
		klazz.belongs_to :requestee
	end
	
	validates_presence_of :requestor, :requestee
	
	alias_attribute :blocked, :restricted
	def accepted?
		!self.restricted
	end
	
	class << self
		alias_attribute :blocked, :restricted
		alias_attribute :unblocked, :unrestricted
	
		alias_attribute :unaccepted, :restricted
		alias_attribute :accepted, :unrestricted
	end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :user_id, presence: true, length: { maximum: 140 }
  belongs_to :user
  default_scope -> { order('created_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  
  acts_as_followable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if user_signed_in?
    @tweet = @user.tweets.build if user_signed_in?
    @tweets = Tweet.all
  end

  def help
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = "Tweeted"
      redirect_to root_path
    else
      flash[:success] = "Tweet failed"
      redirect_to root_path
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @tweets = @user.tweets.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Twitter App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Produced by Life is Tech !
  </small>
  <nav>
    <ul>
      <li><a href="http://life-is-tech.com/">About</a></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Twitter App", root_path, id: "logo" %>
      <nav class="nav-collapse collapse navbar-inverse-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method:'DELETE' %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_tweet_form.html.erb
<%= form_for(@tweet) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new tweet..." %>
  </div>
  <%= f.submit "Tweet", class: "btn btn-large btn-primary" %>
<% end %>

app/views/layouts/_user_info.html.erb
<a href=" <%= user_path(@user) %> ">
  <%= gravatar_for @user %>
</a>
<h1>
  <%= @user.name %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.jp/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'layouts/user_info' %>
      </section>
      <section>
        <%= render 'layouts/tweet_form' %>
      </section>
    </aside>

    <div class="span8">
      <h3>Tweets</h3>
      <ol class="tweets">
        <%= render @tweets %>
      </ol>
    </div>
  </div>
<% else %>
  <div class="center">
    <div class="copy">
      <h1>Life is Tech !</h1>
      <h2>Why don't you change the world ?</h2>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<li>
  <a href="<%= user_path(tweet.user_id) %>">
    <span class="tweetUserName"><%= tweet.user.name %></span>
  </a>
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Tweeted <%= time_ago_in_words(tweet.created_at) %> ago.
  </span>
</li>

app/views/users/_user.html.erb
<li>
  <span>
    <%= user.id %>
  </span>
  <span>
    <a href="<%= user_path(user.id) %>"><%= user.name %></a>
  </span>
</li>

app/views/users/index.html.erb
<ul class="users">
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'layouts/user_info' %> 
    </section>
  </aside>

  <div class="span8">
    <% if @user.tweets.any? %>
      <h3>Tweets (<%= @user.tweets.count %>)</h3>
      <ol class="tweets">
        <%= render @tweets %>
      </ol>
      <%= will_paginate @tweets %>
    <% end %>
  </div>
</div>